// PF PIE Scripts Data - All 98 chapters
const SCRIPT_DATA = {
// ===== Unit 1 =====
1: { // U1-1 Song "Hello! How Are You?"
  en: '<h3>🎵 Hello! How Are You?</h3>',
  ja: '<h3>🎵 こんにちは、ごきげんいかが？</h3><p>こんにちは、こんにちは、ごきげんいかが？（元気だよ！）</p><p>こんにちは、こんにちは、ごきげんいかが？（元気だよ！）</p><p>手を叩こう。足を踏み鳴らそう、膝をたたいて、くるっと回ったら、みんな座ろう</p>'
},
2: { // U1-2 Dialogue "Hi, Henry! (1)"
  en: '<h3>💬 Hi, Henry! (1)</h3><p><span class="speaker">Henry:</span> Hi, Alan!</p><p><span class="speaker">Alan:</span> Hi, Henry! Hi!</p><p><span class="speaker">Nina:</span> Hello.</p><p><span class="speaker">Henry:</span> Hi! What\'s your name?</p><p><span class="speaker">Nina:</span> My name is Nina. What\'s your name?</p><p><span class="speaker">Henry:</span> My name is Henry. Nice to meet you, Nina!</p><p><span class="speaker">Nina:</span> Nice to meet you too, Henry! What\'s your name?</p><p><span class="speaker">Alan:</span> My name is Alan.</p><p><span class="speaker">Nina:</span> Nice to meet you, Alan.</p><p><span class="speaker">Alan:</span> Nice to meet you too. Nina, do you like cats?</p><p><span class="speaker">Nina:</span> No, I don\'t.</p><p><span class="speaker">Alan:</span> Oh. Do you like dogs?</p><p><span class="speaker">Nina:</span> Yes, I do!</p><p><span class="speaker">Alan:</span> Me too.</p><p><span class="speaker">Henry:</span> Let\'s play with my dog after school.</p><p><span class="speaker">A&N&H:</span> Yay!</p>',
  ja: '<h3>💬 やあ、ヘンリー！ (1)</h3><p><span class="speaker">ヘンリー：</span>やあ、アラン！</p><p><span class="speaker">アラン：</span>やあ、ヘンリー！ やあ！</p><p><span class="speaker">ニーナ：</span>こんにちは。</p><p><span class="speaker">ヘンリー：</span>やあ！きみのお名前は？</p><p><span class="speaker">ニーナ：</span>わたしの名前はニーナ。あなたのお名前は？</p><p><span class="speaker">ヘンリー：</span>ぼくの名前はヘンリー。はじめまして、ニーナ！</p><p><span class="speaker">ニーナ：</span>こちらこそ、はじめまして、ヘンリー！あなたのお名前は？</p><p><span class="speaker">アラン：</span>ぼくの名前はアラン。</p><p><span class="speaker">ニーナ：</span>はじめまして、アラン。</p><p><span class="speaker">アラン：</span>こちらこそ、はじめまして。ニーナはネコが好き？</p><p><span class="speaker">ニーナ：</span>ううん、好きではないよ。</p><p><span class="speaker">アラン：</span>そっか。イヌは好き？</p><p><span class="speaker">ニーナ：</span>うん、好き！</p><p><span class="speaker">アラン：</span>ぼくも。</p><p><span class="speaker">ヘンリー：</span>放課後、ぼくのイヌと一緒に遊ぼうよ。</p><p><span class="speaker">全員：</span>やった！</p>'
},
3: { // U1-3 Song "Goodbye"
  en: '<h3>🎵 Goodbye</h3>',
  ja: '<h3>🎵 さようなら</h3><p>さようなら、さようなら、また会いましょう よいひとときを、よいひとときを</p><p>さようなら、さようなら、また会いましょう</p>'
},
4: { // U1-4 Dialogue "Hi, Henry! (2)"
  en: '<h3>💬 Hi, Henry! (2)</h3><p><span class="speaker">Lily:</span> Hi, Nina! I\'m Lily. I\'m Henry\'s sister.</p><p><span class="speaker">Nina:</span> Nice to meet you, Lily! How old are you?</p><p><span class="speaker">Lily:</span> I\'m seven. How old are you, Nina?</p><p><span class="speaker">Nina:</span> I\'m six. What\'s this?</p><p><span class="speaker">Lily:</span> It\'s a rice cracker. Here you are.</p><p><span class="speaker">Nina:</span> Thank you! Yummy! What\'s that?</p><p><span class="speaker">Mr. Brooks:</span> It\'s a mushroom!</p><p><span class="speaker">Lily:</span> That\'s my teacher, Mr. Brooks. Hi, Mr. Brooks!</p><p><span class="speaker">Mr. Brooks:</span> Hi, Lily!</p><p><span class="speaker">Henry:</span> Hi, I\'m Henry.</p><p><span class="speaker">Nina:</span> Hi, I\'m Nina.</p><p><span class="speaker">Mr. Brooks:</span> Nice to meet you, Henry and Nina! How old are you?</p><p><span class="speaker">H&N:</span> I\'m six!</p><p><span class="speaker">Henry:</span> How old are you, Mr. Brooks?</p><p><span class="speaker">Mr. Brooks:</span> Ah ... I\'m one hundred.</p><p><span class="speaker">All:</span> Ha-ha-ha!</p><p><span class="speaker">Henry:</span> No way!</p>',
  ja: '<h3>💬 やあ、ヘンリー！ (2)</h3><p><span class="speaker">リリー：</span>こんにちは、ニーナ！わたしはリリー。ヘンリーの姉よ。</p><p><span class="speaker">ニーナ：</span>はじめまして、リリー！あなたは何歳？</p><p><span class="speaker">リリー：</span>7歳よ。ニーナは何歳？</p><p><span class="speaker">ニーナ：</span>わたしは6歳だよ。これは何？</p><p><span class="speaker">リリー：</span>せんべいだよ。はい、どうぞ。</p><p><span class="speaker">ニーナ：</span>ありがとう！おいしい！あれは何？</p><p><span class="speaker">ブルックス先生：</span>キノコだよ！</p><p><span class="speaker">リリー：</span>あちらはわたしの先生のブルックス先生よ。こんにちは、ブルックス先生！</p><p><span class="speaker">ブルックス先生：</span>やあ、リリー！</p><p><span class="speaker">ヘンリー：</span>こんにちは、ぼくはヘンリーです。</p><p><span class="speaker">ニーナ：</span>こんにちは、わたしはニーナです。</p><p><span class="speaker">ブルックス先生：</span>はじめまして、ヘンリー、ニーナ！きみたちは何歳かな？</p><p><span class="speaker">ヘンリー&ニーナ：</span>6歳です！</p><p><span class="speaker">ヘンリー：</span>ブルックス先生は何歳ですか？</p><p><span class="speaker">ブルックス先生：</span>えっと…100歳さ。</p><p><span class="speaker">全員：</span>ハハハ！</p><p><span class="speaker">ヘンリー：</span>ありえない！</p>'
},
5: { // U1-5 Song "The ABC Song"
  en: '<h3>🎵 The ABC Song</h3>',
  ja: '<h3>🎵 ABCの歌</h3><p>※日本語訳省略</p>'
},
6: { // U1-6 Dialogue "Hi, Henry! (3)"
  en: '<h3>💬 Hi, Henry! (3)</h3><p><span class="speaker">Alan:</span> Hey, look! What\'s that?</p><p><span class="speaker">Nina:</span> Hmm, I don\'t know.</p><p><span class="speaker">Henry:</span> Is that a snake?</p><p><span class="speaker">Alan:</span> Let\'s see.</p><p><span class="speaker">H&A&N:</span> Oh!</p><p><span class="speaker">Alan:</span> A dragon!</p><p><span class="speaker">Nina:</span> Are you OK?</p><p><span class="speaker">Dragon Green:</span> No, I\'m not.</p><p><span class="speaker">Nina:</span> What\'s wrong?</p><p><span class="speaker">Dragon Green:</span> I\'m hungry.</p><p><span class="speaker">H&A&N:</span> Oh ...</p><p><span class="speaker">Dragon Green:</span> I\'m Dragon Green. Do you have a green pepper?</p><p><span class="speaker">Nina:</span> No, I don\'t.</p><p><span class="speaker">Dragon Green:</span> Do you have a cucumber?</p><p><span class="speaker">Nina:</span> No, I don\'t.</p><p><span class="speaker">Dragon Green:</span> Do you have a green mushroom?</p><p><span class="speaker">Nina:</span> No, I don\'t.</p><p><span class="speaker">Mr. Brooks:</span> Yes, I do! Here you are.</p><p><span class="speaker">Dragon Green:</span> Wow! Thank you!</p>',
  ja: '<h3>💬 やあ、ヘンリー！ (3)</h3><p><span class="speaker">アラン：</span>ねえ、見て！あれは何？</p><p><span class="speaker">ニーナ：</span>うーん、わからないなあ。</p><p><span class="speaker">ヘンリー：</span>あれはヘビかな？</p><p><span class="speaker">アラン：</span>見てみよう。</p><p><span class="speaker">全員：</span>わあ！</p><p><span class="speaker">アラン：</span>ドラゴンだ！</p><p><span class="speaker">ニーナ：</span>大丈夫？</p><p><span class="speaker">ドラゴングリーン：</span>ううん。</p><p><span class="speaker">ニーナ：</span>どうしたの？</p><p><span class="speaker">ドラゴングリーン：</span>お腹がすいているんだ。</p><p><span class="speaker">全員：</span>ああ…。</p><p><span class="speaker">ドラゴングリーン：</span>ぼくはドラゴングリーン。ピーマンを持っているかい？</p><p><span class="speaker">ニーナ：</span>持っていないよ。</p><p><span class="speaker">ドラゴングリーン：</span>キュウリは持っているかい？</p><p><span class="speaker">ニーナ：</span>持っていないよ。</p><p><span class="speaker">ドラゴングリーン：</span>緑のキノコは持っているかい？</p><p><span class="speaker">ニーナ：</span>持っていないよ。</p><p><span class="speaker">ブルックス先生：</span>持っているよ！はい、どうぞ。</p><p><span class="speaker">ドラゴングリーン：</span>わあ！ありがとう！</p>'
},
7: { // U1-7 Practice Q&A + My Speech (combined)
  en: '<h3>🎯 Questions and Answers / My Speech</h3><p><span class="speaker">Instructor:</span> What\'s your name?</p><p><span class="speaker">Riko:</span> My name is Riko.</p><p><span class="speaker">Instructor:</span> How old are you?</p><p><span class="speaker">Riko:</span> I\'m seven.</p><p><span class="speaker">Instructor:</span> Where do you live?</p><p><span class="speaker">Riko:</span> I live in Naha City.</p><p><span class="speaker">Instructor:</span> How\'s the weather today?</p><p><span class="speaker">Riko:</span> It\'s cloudy.</p><hr><p><span class="speaker">Riko:</span> Hello. My name is Riko. I\'m seven. I live in Naha City. Thank you.</p>',
  ja: '<h3>🎯 質問と答え / マイスピーチ</h3><p><span class="speaker">講師：</span>あなたの名前は何ですか？</p><p><span class="speaker">りこ：</span>わたしの名前はりこです。</p><p><span class="speaker">講師：</span>何歳ですか？</p><p><span class="speaker">りこ：</span>7歳です。</p><p><span class="speaker">講師：</span>どこに住んでいますか？</p><p><span class="speaker">りこ：</span>那覇市です。</p><p><span class="speaker">講師：</span>今日はどんな天気ですか？</p><p><span class="speaker">りこ：</span>曇りです。</p><hr><p><span class="speaker">りこ：</span>こんにちは。わたしの名前はりこです。7歳です。那覇市に住んでいます。ありがとうございました。</p>'
},
8: { // U1-8 Dialogue "Hi, Henry! (4)"
  en: '<h3>💬 Hi, Henry! (4)</h3><p><span class="speaker">Alan:</span> We\'re late!</p><p><span class="speaker">H&A&N:</span> Ooh ... Oh no!</p><p><span class="speaker">Nina:</span> Is this your pencil?</p><p><span class="speaker">Henry:</span> Yes, it is. Thank you.</p><p><span class="speaker">Nina:</span> Is this your notebook?</p><p><span class="speaker">Alan:</span> Yes, it is. Thank you.</p><p><span class="speaker">Henry:</span> Is this your eraser?</p><p><span class="speaker">Nina:</span> No, it\'s not.</p><p><span class="speaker">Henry:</span> Is this your eraser, Alan?</p><p><span class="speaker">Alan:</span> No, it\'s not.</p><p><span class="speaker">H&A&N:</span> Hmm?</p><p><span class="speaker">Mr. Brooks:</span> Ah, there it is!</p><p><span class="speaker">Henry:</span> Is this your eraser?</p><p><span class="speaker">Mr. Brooks:</span> Yes, it is. Thank you, Henry!</p><p><span class="speaker">Henry:</span> You\'re welcome!</p>',
  ja: '<h3>💬 やあ、ヘンリー！ (4)</h3><p><span class="speaker">アラン：</span>遅刻だ！</p><p><span class="speaker">全員：</span>うー。あーあ！</p><p><span class="speaker">ニーナ：</span>これはあなたの鉛筆？</p><p><span class="speaker">ヘンリー：</span>うん、そうだよ。ありがとう。</p><p><span class="speaker">ニーナ：</span>これはあなたのノート？</p><p><span class="speaker">アラン：</span>うん、そうだよ。ありがとう。</p><p><span class="speaker">ヘンリー：</span>これはきみの消しゴム？</p><p><span class="speaker">ニーナ：</span>ううん、ちがうよ。</p><p><span class="speaker">ヘンリー：</span>これはきみの消しゴムかい、アラン？</p><p><span class="speaker">アラン：</span>ううん、ちがうよ。</p><p><span class="speaker">全員：</span>うーん？</p><p><span class="speaker">ブルックス先生：</span>ああ、そこにあったのか！</p><p><span class="speaker">ヘンリー：</span>これはあなたの消しゴムですか？</p><p><span class="speaker">ブルックス先生：</span>うん、そうさ。ありがとう、ヘンリー！</p><p><span class="speaker">ヘンリー：</span>どういたしまして！</p>'
},
9: { // U1-9 Keyword Chants (combined)
  en: '<h3>🎶 Keyword Chants: You and I / My and Your</h3><p>※日本語訳省略</p>',
  ja: '<h3>🎶 キーワードチャンツ</h3><p>※日本語訳省略</p>'
},
10: { // U1-10 Think Globally "Baby Animals"
  en: '<h3>🌍 Baby Animals</h3><p><span class="speaker">Ms. Wilson:</span> Wow! Look at the baby penguins. They\'re so fluffy! Let\'s go see some baby animals around the world!</p><p><span class="speaker">Woman:</span> In Rwanda, we see gorillas. The mother gorilla is taking care of her baby.</p><p><span class="speaker">Woman:</span> In Russia, we see Amur leopards. The leopard cubs are wrestling and biting each other.</p><p><span class="speaker">Woman:</span> In Canada, we see red foxes. The fox cubs look happy with their family.</p><p><span class="speaker">Woman:</span> In Botswana, we see giraffes. The baby giraffe is drinking milk and the mother giraffe is kissing her baby.</p><p><span class="speaker">Woman:</span> In Germany, we see wild boars. They\'re looking for some food in the forest.</p><p><span class="speaker">Ms. Wilson:</span> Baby animals are always full of energy! Which baby animal did you like the best?</p>',
  ja: '<h3>🌍 動物の赤ちゃん</h3><p><span class="speaker">ウィルソン先生：</span>わあ！ペンギンの赤ちゃんを見てください。とてもフワフワしていますね！世界中の動物の赤ちゃんを見に行きましょう！</p><p><span class="speaker">女性：</span>ルワンダには、ゴリラがいます。お母さんゴリラが赤ちゃんの面倒を見ています。</p><p><span class="speaker">女性：</span>ロシアには、アムールヒョウがいます。ヒョウの赤ちゃんがレスリングをしたり、かみ合ったりしています。</p><p><span class="speaker">女性：</span>カナダには、アカギツネがいます。キツネの赤ちゃんは家族と一緒でうれしそうです。</p><p><span class="speaker">女性：</span>ボツワナには、キリンがいます。キリンの赤ちゃんがお乳を飲み、お母さんが赤ちゃんにキスをしています。</p><p><span class="speaker">女性：</span>ドイツには、イノシシがいます。森の中で、食料を探しています。</p><p><span class="speaker">ウィルソン先生：</span>動物の赤ちゃんはいつも元気いっぱいです！あなたはどの赤ちゃんが一番気に入りましたか？</p>'
},
11: { // U1-11 Keyword Chants (combined)
  en: '<h3>🎶 Keyword Chants: He and She / On, In, Under</h3><p>※日本語訳省略</p>',
  ja: '<h3>🎶 キーワードチャンツ</h3><p>※日本語訳省略</p>'
},
12: { // U1-12 Song "The Hokey-Pokey"
  en: '<h3>🎵 The Hokey-Pokey</h3>',
  ja: '<h3>🎵 ホーキー・ポーキー</h3><p>1. 右手を入れて、右手を出して、右手を入れて、振りましょう。ホーキー・ポーキーをして、ぐるっと回ろう、そういうことなのさ！</p><p>2. 左手</p><p>3. お腹</p><p>4. おしり</p><p>5. からだ全部</p>'
},
};
