// PF PIE Scripts Data - All 98 chapters
const SCRIPT_DATA = {
// ===== Unit 1 =====
1: { // U1-1 Song "Hello! How Are You?"
  en: '<h3>🎵 Hello! How Are You?</h3>',
  ja: '<h3>🎵 こんにちは、ごきげんいかが？</h3><p>こんにちは、こんにちは、ごきげんいかが？（元気だよ！）</p><p>こんにちは、こんにちは、ごきげんいかが？（元気だよ！）</p><p>手を叩こう。足を踏み鳴らそう、膝をたたいて、くるっと回ったら、みんな座ろう</p>'
},
2: { // U1-2 Dialogue "Hi, Henry! (1)"
  en: '<h3>💬 Hi, Henry! (1)</h3><p><span class="speaker">Henry:</span> Hi, Alan!</p><p><span class="speaker">Alan:</span> Hi, Henry! Hi!</p><p><span class="speaker">Nina:</span> Hello.</p><p><span class="speaker">Henry:</span> Hi! What\'s your name?</p><p><span class="speaker">Nina:</span> My name is Nina. What\'s your name?</p><p><span class="speaker">Henry:</span> My name is Henry. Nice to meet you, Nina!</p><p><span class="speaker">Nina:</span> Nice to meet you too, Henry! What\'s your name?</p><p><span class="speaker">Alan:</span> My name is Alan.</p><p><span class="speaker">Nina:</span> Nice to meet you, Alan.</p><p><span class="speaker">Alan:</span> Nice to meet you too. Nina, do you like cats?</p><p><span class="speaker">Nina:</span> No, I don\'t.</p><p><span class="speaker">Alan:</span> Oh. Do you like dogs?</p><p><span class="speaker">Nina:</span> Yes, I do!</p><p><span class="speaker">Alan:</span> Me too.</p><p><span class="speaker">Henry:</span> Let\'s play with my dog after school.</p><p><span class="speaker">A&N&H:</span> Yay!</p>',
  ja: '<h3>💬 やあ、ヘンリー！ (1)</h3><p><span class="speaker">ヘンリー：</span>やあ、アラン！</p><p><span class="speaker">アラン：</span>やあ、ヘンリー！ やあ！</p><p><span class="speaker">ニーナ：</span>こんにちは。</p><p><span class="speaker">ヘンリー：</span>やあ！きみのお名前は？</p><p><span class="speaker">ニーナ：</span>わたしの名前はニーナ。あなたのお名前は？</p><p><span class="speaker">ヘンリー：</span>ぼくの名前はヘンリー。はじめまして、ニーナ！</p><p><span class="speaker">ニーナ：</span>こちらこそ、はじめまして、ヘンリー！あなたのお名前は？</p><p><span class="speaker">アラン：</span>ぼくの名前はアラン。</p><p><span class="speaker">ニーナ：</span>はじめまして、アラン。</p><p><span class="speaker">アラン：</span>こちらこそ、はじめまして。ニーナはネコが好き？</p><p><span class="speaker">ニーナ：</span>ううん、好きではないよ。</p><p><span class="speaker">アラン：</span>そっか。イヌは好き？</p><p><span class="speaker">ニーナ：</span>うん、好き！</p><p><span class="speaker">アラン：</span>ぼくも。</p><p><span class="speaker">ヘンリー：</span>放課後、ぼくのイヌと一緒に遊ぼうよ。</p><p><span class="speaker">全員：</span>やった！</p>'
},
3: { // U1-3 Song "Goodbye"
  en: '<h3>🎵 Goodbye</h3>',
  ja: '<h3>🎵 さようなら</h3><p>さようなら、さようなら、また会いましょう よいひとときを、よいひとときを</p><p>さようなら、さようなら、また会いましょう</p>'
},
4: { // U1-4 Dialogue "Hi, Henry! (2)"
  en: '<h3>💬 Hi, Henry! (2)</h3><p><span class="speaker">Lily:</span> Hi, Nina! I\'m Lily. I\'m Henry\'s sister.</p><p><span class="speaker">Nina:</span> Nice to meet you, Lily! How old are you?</p><p><span class="speaker">Lily:</span> I\'m seven. How old are you, Nina?</p><p><span class="speaker">Nina:</span> I\'m six. What\'s this?</p><p><span class="speaker">Lily:</span> It\'s a rice cracker. Here you are.</p><p><span class="speaker">Nina:</span> Thank you! Yummy! What\'s that?</p><p><span class="speaker">Mr. Brooks:</span> It\'s a mushroom!</p><p><span class="speaker">Lily:</span> That\'s my teacher, Mr. Brooks. Hi, Mr. Brooks!</p><p><span class="speaker">Mr. Brooks:</span> Hi, Lily!</p><p><span class="speaker">Henry:</span> Hi, I\'m Henry.</p><p><span class="speaker">Nina:</span> Hi, I\'m Nina.</p><p><span class="speaker">Mr. Brooks:</span> Nice to meet you, Henry and Nina! How old are you?</p><p><span class="speaker">H&N:</span> I\'m six!</p><p><span class="speaker">Henry:</span> How old are you, Mr. Brooks?</p><p><span class="speaker">Mr. Brooks:</span> Ah ... I\'m one hundred.</p><p><span class="speaker">All:</span> Ha-ha-ha!</p><p><span class="speaker">Henry:</span> No way!</p>',
  ja: '<h3>💬 やあ、ヘンリー！ (2)</h3><p><span class="speaker">リリー：</span>こんにちは、ニーナ！わたしはリリー。ヘンリーの姉よ。</p><p><span class="speaker">ニーナ：</span>はじめまして、リリー！あなたは何歳？</p><p><span class="speaker">リリー：</span>7歳よ。ニーナは何歳？</p><p><span class="speaker">ニーナ：</span>わたしは6歳だよ。これは何？</p><p><span class="speaker">リリー：</span>せんべいだよ。はい、どうぞ。</p><p><span class="speaker">ニーナ：</span>ありがとう！おいしい！あれは何？</p><p><span class="speaker">ブルックス先生：</span>キノコだよ！</p><p><span class="speaker">リリー：</span>あちらはわたしの先生のブルックス先生よ。こんにちは、ブルックス先生！</p><p><span class="speaker">ブルックス先生：</span>やあ、リリー！</p><p><span class="speaker">ヘンリー：</span>こんにちは、ぼくはヘンリーです。</p><p><span class="speaker">ニーナ：</span>こんにちは、わたしはニーナです。</p><p><span class="speaker">ブルックス先生：</span>はじめまして、ヘンリー、ニーナ！きみたちは何歳かな？</p><p><span class="speaker">ヘンリー&ニーナ：</span>6歳です！</p><p><span class="speaker">ヘンリー：</span>ブルックス先生は何歳ですか？</p><p><span class="speaker">ブルックス先生：</span>えっと…100歳さ。</p><p><span class="speaker">全員：</span>ハハハ！</p><p><span class="speaker">ヘンリー：</span>ありえない！</p>'
},
5: { // U1-5 Song "The ABC Song"
  en: '<h3>🎵 The ABC Song</h3>',
  ja: '<h3>🎵 ABCの歌</h3><p>※日本語訳省略</p>'
},
6: { // U1-6 Dialogue "Hi, Henry! (3)"
  en: '<h3>💬 Hi, Henry! (3)</h3><p><span class="speaker">Alan:</span> Hey, look! What\'s that?</p><p><span class="speaker">Nina:</span> Hmm, I don\'t know.</p><p><span class="speaker">Henry:</span> Is that a snake?</p><p><span class="speaker">Alan:</span> Let\'s see.</p><p><span class="speaker">H&A&N:</span> Oh!</p><p><span class="speaker">Alan:</span> A dragon!</p><p><span class="speaker">Nina:</span> Are you OK?</p><p><span class="speaker">Dragon Green:</span> No, I\'m not.</p><p><span class="speaker">Nina:</span> What\'s wrong?</p><p><span class="speaker">Dragon Green:</span> I\'m hungry.</p><p><span class="speaker">H&A&N:</span> Oh ...</p><p><span class="speaker">Dragon Green:</span> I\'m Dragon Green. Do you have a green pepper?</p><p><span class="speaker">Nina:</span> No, I don\'t.</p><p><span class="speaker">Dragon Green:</span> Do you have a cucumber?</p><p><span class="speaker">Nina:</span> No, I don\'t.</p><p><span class="speaker">Dragon Green:</span> Do you have a green mushroom?</p><p><span class="speaker">Nina:</span> No, I don\'t.</p><p><span class="speaker">Mr. Brooks:</span> Yes, I do! Here you are.</p><p><span class="speaker">Dragon Green:</span> Wow! Thank you!</p>',
  ja: '<h3>💬 やあ、ヘンリー！ (3)</h3><p><span class="speaker">アラン：</span>ねえ、見て！あれは何？</p><p><span class="speaker">ニーナ：</span>うーん、わからないなあ。</p><p><span class="speaker">ヘンリー：</span>あれはヘビかな？</p><p><span class="speaker">アラン：</span>見てみよう。</p><p><span class="speaker">全員：</span>わあ！</p><p><span class="speaker">アラン：</span>ドラゴンだ！</p><p><span class="speaker">ニーナ：</span>大丈夫？</p><p><span class="speaker">ドラゴングリーン：</span>ううん。</p><p><span class="speaker">ニーナ：</span>どうしたの？</p><p><span class="speaker">ドラゴングリーン：</span>お腹がすいているんだ。</p><p><span class="speaker">全員：</span>ああ…。</p><p><span class="speaker">ドラゴングリーン：</span>ぼくはドラゴングリーン。ピーマンを持っているかい？</p><p><span class="speaker">ニーナ：</span>持っていないよ。</p><p><span class="speaker">ドラゴングリーン：</span>キュウリは持っているかい？</p><p><span class="speaker">ニーナ：</span>持っていないよ。</p><p><span class="speaker">ドラゴングリーン：</span>緑のキノコは持っているかい？</p><p><span class="speaker">ニーナ：</span>持っていないよ。</p><p><span class="speaker">ブルックス先生：</span>持っているよ！はい、どうぞ。</p><p><span class="speaker">ドラゴングリーン：</span>わあ！ありがとう！</p>'
},
7: { // U1-7 Practice Q&A + My Speech (combined)
  en: '<h3>🎯 Questions and Answers / My Speech</h3><p><span class="speaker">Instructor:</span> What\'s your name?</p><p><span class="speaker">Riko:</span> My name is Riko.</p><p><span class="speaker">Instructor:</span> How old are you?</p><p><span class="speaker">Riko:</span> I\'m seven.</p><p><span class="speaker">Instructor:</span> Where do you live?</p><p><span class="speaker">Riko:</span> I live in Naha City.</p><p><span class="speaker">Instructor:</span> How\'s the weather today?</p><p><span class="speaker">Riko:</span> It\'s cloudy.</p><hr><p><span class="speaker">Riko:</span> Hello. My name is Riko. I\'m seven. I live in Naha City. Thank you.</p>',
  ja: '<h3>🎯 質問と答え / マイスピーチ</h3><p><span class="speaker">講師：</span>あなたの名前は何ですか？</p><p><span class="speaker">りこ：</span>わたしの名前はりこです。</p><p><span class="speaker">講師：</span>何歳ですか？</p><p><span class="speaker">りこ：</span>7歳です。</p><p><span class="speaker">講師：</span>どこに住んでいますか？</p><p><span class="speaker">りこ：</span>那覇市です。</p><p><span class="speaker">講師：</span>今日はどんな天気ですか？</p><p><span class="speaker">りこ：</span>曇りです。</p><hr><p><span class="speaker">りこ：</span>こんにちは。わたしの名前はりこです。7歳です。那覇市に住んでいます。ありがとうございました。</p>'
},
8: { // U1-8 Dialogue "Hi, Henry! (4)"
  en: '<h3>💬 Hi, Henry! (4)</h3><p><span class="speaker">Alan:</span> We\'re late!</p><p><span class="speaker">H&A&N:</span> Ooh ... Oh no!</p><p><span class="speaker">Nina:</span> Is this your pencil?</p><p><span class="speaker">Henry:</span> Yes, it is. Thank you.</p><p><span class="speaker">Nina:</span> Is this your notebook?</p><p><span class="speaker">Alan:</span> Yes, it is. Thank you.</p><p><span class="speaker">Henry:</span> Is this your eraser?</p><p><span class="speaker">Nina:</span> No, it\'s not.</p><p><span class="speaker">Henry:</span> Is this your eraser, Alan?</p><p><span class="speaker">Alan:</span> No, it\'s not.</p><p><span class="speaker">H&A&N:</span> Hmm?</p><p><span class="speaker">Mr. Brooks:</span> Ah, there it is!</p><p><span class="speaker">Henry:</span> Is this your eraser?</p><p><span class="speaker">Mr. Brooks:</span> Yes, it is. Thank you, Henry!</p><p><span class="speaker">Henry:</span> You\'re welcome!</p>',
  ja: '<h3>💬 やあ、ヘンリー！ (4)</h3><p><span class="speaker">アラン：</span>遅刻だ！</p><p><span class="speaker">全員：</span>うー。あーあ！</p><p><span class="speaker">ニーナ：</span>これはあなたの鉛筆？</p><p><span class="speaker">ヘンリー：</span>うん、そうだよ。ありがとう。</p><p><span class="speaker">ニーナ：</span>これはあなたのノート？</p><p><span class="speaker">アラン：</span>うん、そうだよ。ありがとう。</p><p><span class="speaker">ヘンリー：</span>これはきみの消しゴム？</p><p><span class="speaker">ニーナ：</span>ううん、ちがうよ。</p><p><span class="speaker">ヘンリー：</span>これはきみの消しゴムかい、アラン？</p><p><span class="speaker">アラン：</span>ううん、ちがうよ。</p><p><span class="speaker">全員：</span>うーん？</p><p><span class="speaker">ブルックス先生：</span>ああ、そこにあったのか！</p><p><span class="speaker">ヘンリー：</span>これはあなたの消しゴムですか？</p><p><span class="speaker">ブルックス先生：</span>うん、そうさ。ありがとう、ヘンリー！</p><p><span class="speaker">ヘンリー：</span>どういたしまして！</p>'
},
9: { // U1-9 Keyword Chants (combined)
  en: '<h3>🎶 Keyword Chants: You and I / My and Your</h3><p>※日本語訳省略</p>',
  ja: '<h3>🎶 キーワードチャンツ</h3><p>※日本語訳省略</p>'
},
10: { // U1-10 Think Globally "Baby Animals"
  en: '<h3>🌍 Baby Animals</h3><p><span class="speaker">Ms. Wilson:</span> Wow! Look at the baby penguins. They\'re so fluffy! Let\'s go see some baby animals around the world!</p><p><span class="speaker">Woman:</span> In Rwanda, we see gorillas. The mother gorilla is taking care of her baby.</p><p><span class="speaker">Woman:</span> In Russia, we see Amur leopards. The leopard cubs are wrestling and biting each other.</p><p><span class="speaker">Woman:</span> In Canada, we see red foxes. The fox cubs look happy with their family.</p><p><span class="speaker">Woman:</span> In Botswana, we see giraffes. The baby giraffe is drinking milk and the mother giraffe is kissing her baby.</p><p><span class="speaker">Woman:</span> In Germany, we see wild boars. They\'re looking for some food in the forest.</p><p><span class="speaker">Ms. Wilson:</span> Baby animals are always full of energy! Which baby animal did you like the best?</p>',
  ja: '<h3>🌍 動物の赤ちゃん</h3><p><span class="speaker">ウィルソン先生：</span>わあ！ペンギンの赤ちゃんを見てください。とてもフワフワしていますね！世界中の動物の赤ちゃんを見に行きましょう！</p><p><span class="speaker">女性：</span>ルワンダには、ゴリラがいます。お母さんゴリラが赤ちゃんの面倒を見ています。</p><p><span class="speaker">女性：</span>ロシアには、アムールヒョウがいます。ヒョウの赤ちゃんがレスリングをしたり、かみ合ったりしています。</p><p><span class="speaker">女性：</span>カナダには、アカギツネがいます。キツネの赤ちゃんは家族と一緒でうれしそうです。</p><p><span class="speaker">女性：</span>ボツワナには、キリンがいます。キリンの赤ちゃんがお乳を飲み、お母さんが赤ちゃんにキスをしています。</p><p><span class="speaker">女性：</span>ドイツには、イノシシがいます。森の中で、食料を探しています。</p><p><span class="speaker">ウィルソン先生：</span>動物の赤ちゃんはいつも元気いっぱいです！あなたはどの赤ちゃんが一番気に入りましたか？</p>'
},
11: { // U1-11 Keyword Chants (combined)
  en: '<h3>🎶 Keyword Chants: He and She / On, In, Under</h3><p>※日本語訳省略</p>',
  ja: '<h3>🎶 キーワードチャンツ</h3><p>※日本語訳省略</p>'
},
12: { // U1-12 Song "The Hokey-Pokey"
  en: '<h3>🎵 The Hokey-Pokey</h3>',
  ja: '<h3>🎵 ホーキー・ポーキー</h3><p>1. 右手を入れて、右手を出して、右手を入れて、振りましょう。ホーキー・ポーキーをして、ぐるっと回ろう、そういうことなのさ！</p><p>2. 左手</p><p>3. お腹</p><p>4. おしり</p><p>5. からだ全部</p>'
},
// ===== Unit 2 =====
13: { en: '<h3>💬 Hi, Henry! (5)</h3><p><span class="speaker">Ms. Moore:</span> What a mess! Huh? Whose glue is this?</p><p><span class="speaker">Lily:</span> It\'s mine.</p><p><span class="speaker">Ms. Moore:</span> Here you are.</p><p><span class="speaker">Lily:</span> Thank you.</p><p><span class="speaker">Ms. Moore:</span> Whose umbrella is this?</p><p><span class="speaker">Lily:</span> It\'s Henry\'s. Henry! Come and get your umbrella!</p><p><span class="speaker">Henry:</span> Thanks, Mom.</p><p><span class="speaker">Ms. Moore:</span> Please keep the living room clean.</p><p><span class="speaker">Henry:</span> OK. Mom, whose bag is this?</p><p><span class="speaker">Ms. Moore:</span> Oh, it\'s mine. I use it for my dance class.</p><p><span class="speaker">Lily:</span> Please keep the living room clean, Mom!</p><p><span class="speaker">Ms. Moore:</span> You\'re right.</p>', ja: '<h3>💬 やあ、ヘンリー！ (5)</h3><p><span class="speaker">ムーアさん：</span>なんて散らかっているの！ あら？これは誰ののりかしら？</p><p><span class="speaker">リリー：</span>わたしのだよ。</p><p><span class="speaker">ムーアさん：</span>はい、どうぞ。</p><p><span class="speaker">リリー：</span>ありがとう。</p><p><span class="speaker">ムーアさん：</span>これは誰の傘？</p><p><span class="speaker">リリー：</span>ヘンリーのだよ。ヘンリー！ 傘を取りに来て！</p><p><span class="speaker">ヘンリー：</span>ありがとう、ママ。</p><p><span class="speaker">ムーアさん：</span>リビングルームはきれいにね。</p><p><span class="speaker">ヘンリー：</span>わかった。ママ、これは誰のバッグ？</p><p><span class="speaker">ムーアさん：</span>あら、わたしのだわ。ダンスのクラスに使うのよ。</p><p><span class="speaker">リリー：</span>リビングルームはきれいにね、ママ！</p><p><span class="speaker">ムーアさん：</span>そのとおりね。</p>' },
14: { en: '<h3>💬 Hi, Henry! (6)</h3><p><span class="speaker">Alan:</span> Mmm. Yummy.</p><p><span class="speaker">Nina:</span> Yeah.</p><p><span class="speaker">Henry:</span> Nina, watch out!</p><p><span class="speaker">Nina:</span> What? Aah! My cookies are gone ...</p><p><span class="speaker">Alan:</span> Are you angry?</p><p><span class="speaker">Nina:</span> No, I\'m not.</p><p><span class="speaker">Alan:</span> Are you sad?</p><p><span class="speaker">Nina:</span> Yes, I am.</p><p><span class="speaker">Henry:</span> Hey, let\'s share.</p><p><span class="speaker">Alan:</span> That\'s a good idea.</p><p><span class="speaker">Nina:</span> Wow. Thanks.</p><p><span class="speaker">Alan:</span> Are you happy?</p><p><span class="speaker">Nina:</span> Yes, I am. Thank you.</p><p><span class="speaker">Alan:</span> You\'re welcome.</p>', ja: '<h3>💬 やあ、ヘンリー！ (6)</h3><p><span class="speaker">アラン：</span>うーん。おいしいな。</p><p><span class="speaker">ニーナ：</span>うん。</p><p><span class="speaker">ヘンリー：</span>ニーナ、気をつけて！</p><p><span class="speaker">ニーナ：</span>え？ キャーッ！ わたしのクッキー、なくなっちゃった…。</p><p><span class="speaker">アラン：</span>怒ってる？</p><p><span class="speaker">ニーナ：</span>ううん、怒ってないよ。</p><p><span class="speaker">アラン：</span>悲しい？</p><p><span class="speaker">ニーナ：</span>うん、悲しい。</p><p><span class="speaker">ヘンリー：</span>ねえ、分けっこしよう。</p><p><span class="speaker">アラン：</span>いいね。</p><p><span class="speaker">ニーナ：</span>わあ。ありがとう。</p><p><span class="speaker">アラン：</span>うれしい？</p><p><span class="speaker">ニーナ：</span>うん、うれしい。ありがとう。</p><p><span class="speaker">アラン：</span>どういたしまして。</p>' },
15: { en: '<h3>💬 Hi, Henry! (7)</h3><p><span class="speaker">Dragon Green:</span> Welcome, everybody.</p><p><span class="speaker">Alan:</span> Thank you for inviting us.</p><p><span class="speaker">Henry:</span> There\'re so many green things.</p><p><span class="speaker">Dragon Green:</span> Of course. I\'m Dragon Green.</p><p><span class="speaker">Alan:</span> What are those?</p><p><span class="speaker">Dragon Green:</span> They\'re cushions. Have a seat. Please have a snack.</p><p><span class="speaker">Nina:</span> What are these?</p><p><span class="speaker">Dragon Green:</span> They\'re marshmallows. They\'re green pepper marshmallows.</p><p><span class="speaker">Nina:</span> Wow! They taste funny.</p><p><span class="speaker">Alan:</span> Really? Yeah.</p><p><span class="speaker">Henry:</span> What are those?</p><p><span class="speaker">Dragon Green:</span> They\'re bananas.</p><p><span class="speaker">Henry:</span> They\'re still green!</p><p><span class="speaker">Dragon Green:</span> Of course. I\'m Dragon Green. I like green bananas.</p>', ja: '<h3>💬 やあ、ヘンリー！ (7)</h3><p><span class="speaker">ドラゴングリーン：</span>いらっしゃい、みなさん。</p><p><span class="speaker">アラン：</span>お招きありがとう。</p><p><span class="speaker">ヘンリー：</span>緑色のものがたくさんあるね。</p><p><span class="speaker">ドラゴングリーン：</span>もちろんだよ。ぼくはドラコングリーンだもん。</p><p><span class="speaker">アラン：</span>あれらは何？</p><p><span class="speaker">ドラゴングリーン：</span>クッションだよ。座って。おやつをどうぞ。</p><p><span class="speaker">ニーナ：</span>これらは何？</p><p><span class="speaker">ドラゴングリーン：</span>マシュマロだよ。ピーマンマシュマロだよ。</p><p><span class="speaker">ニーナ：</span>わあ！ 変わった味がする。</p><p><span class="speaker">アラン：</span>本当に？ そうだね。</p><p><span class="speaker">ヘンリー：</span>あれらは何？</p><p><span class="speaker">ドラゴングリーン：</span>バナナだよ。</p><p><span class="speaker">ヘンリー：</span>まだ緑色だよ！</p><p><span class="speaker">ドラゴングリーン：</span>そりゃあそうだよね。ぼくはドラコングリーンだもん。ぼくは緑色のバナナが好きなんだ。</p>' },
16: { en: '<h3>🎵 The Phonics Song</h3>', ja: '<h3>🎵 フォニックスの歌</h3><p>※日本語訳省略</p>' },
17: { en: '<h3>💬 Hi, Henry! (8)</h3><p><span class="speaker">Ms. Moore:</span> OK, kids. Order anything you want.</p><p><span class="speaker">H&L:</span> Yay!</p><p><span class="speaker">Ms. Moore:</span> Henry, what do you want?</p><p><span class="speaker">Henry:</span> I want a muffin!</p><p><span class="speaker">Ms. Moore:</span> OK. Lily, what do you want?</p><p><span class="speaker">Lily:</span> I want some cookies!</p><p><span class="speaker">Ms. Moore:</span> OK. Hmm, those cakes look delicious. Aah!</p><p><span class="speaker">Dragon Green:</span> Hi, everyone!</p><p><span class="speaker">H&L:</span> Hi, Dragon Green!</p>', ja: '<h3>💬 やあ、ヘンリー！ (8)</h3><p><span class="speaker">ムーアさん：</span>さあ、みんな。好きなものを注文しなさい。</p><p><span class="speaker">ヘ&リ：</span>やった！</p><p><span class="speaker">ムーアさん：</span>ヘンリー、何が欲しい？</p><p><span class="speaker">ヘンリー：</span>ぼくはマフィンがひとつ欲しい！</p><p><span class="speaker">ムーアさん：</span>いいわ。リリー、あなたは何が欲しい？</p><p><span class="speaker">リリー：</span>わたしはクッキーがいくつか欲しい！</p><p><span class="speaker">ムーアさん：</span>いいわよ。ふむ、どのケーキもおいしそうね。ああ！</p><p><span class="speaker">ドラゴングリーン：</span>やあ、みんな！</p><p><span class="speaker">ヘ&リ：</span>やあ、ドラゴングリーン！</p>' },
18: { en: '<h3>💬 Hi, Henry! (9)</h3><p><span class="speaker">Lily:</span> Hey, Henry! What a mess!</p><p><span class="speaker">Henry:</span> Ha-ha, sorry. I was playing with Jackie.</p><p><span class="speaker">Lily:</span> You have to clean up before Mom comes home.</p><p><span class="speaker">Henry:</span> You\'re right.</p><p><span class="speaker">Lily:</span> Well, where\'s the basket?</p><p><span class="speaker">Henry:</span> On the chair.</p><p><span class="speaker">Lily:</span> Where\'s the cushion?</p><p><span class="speaker">Henry:</span> In the basket.</p><p><span class="speaker">Lily:</span> Unbelievable! Where\'s the trash can?</p><p><span class="speaker">Henry:</span> Under the table.</p><p><span class="speaker">Lily:</span> And where\'s Jackie?</p><p><span class="speaker">Henry:</span> Hmm? Oh, he\'s under the rug!</p>', ja: '<h3>💬 やあ、ヘンリー！ (9)</h3><p><span class="speaker">リリー：</span>ちょっと、ヘンリー！なんて散らかっているの！</p><p><span class="speaker">ヘンリー：</span>ハハ、ごめんよ。ジャッキーと遊んでいたんだ。</p><p><span class="speaker">リリー：</span>ママが帰って来る前に片付けなきゃ。</p><p><span class="speaker">ヘンリー：</span>そうだね。</p><p><span class="speaker">リリー：</span>えーっと、バスケットはどこ？</p><p><span class="speaker">ヘンリー：</span>いすの上だよ。</p><p><span class="speaker">リリー：</span>クッションはどこ？</p><p><span class="speaker">ヘンリー：</span>バスケットの中だよ。</p><p><span class="speaker">リリー：</span>信じられない！ゴミ箱はどこ？</p><p><span class="speaker">ヘンリー：</span>テーブルの下だよ。</p><p><span class="speaker">リリー：</span>それに、ジャッキーはどこ？</p><p><span class="speaker">ヘンリー：</span>あれ？あ、敷物の下だ！</p>' },
19: { en: '<h3>🔤 Phonics: a, b, c</h3><p>ant - alligator</p><p>book - bag</p><p>cat - cabbage</p>', ja: '<h3>🔤 フォニックス: a, b, c</h3><p>ant - アリ / alligator - ワニ</p><p>book - 本 / bag - かばん</p><p>cat - ネコ / cabbage - キャベツ</p>' },
20: { en: '<h3>🎯 Questions and Answers / My Speech</h3><p><span class="speaker">Instructor:</span> Where do you go to school?</p><p><span class="speaker">Riko:</span> I go to Aoba Elementary School.</p><p><span class="speaker">Instructor:</span> What grade are you in?</p><p><span class="speaker">Riko:</span> I\'m in the second grade.</p><p><span class="speaker">Instructor:</span> Who\'s your homeroom teacher?</p><p><span class="speaker">Riko:</span> Mr. Sakai.</p><p><span class="speaker">Instructor:</span> What day is it today?</p><p><span class="speaker">Riko:</span> It\'s Wednesday.</p><hr><p><span class="speaker">Riko:</span> Hello. My name is Riko. I\'m seven. I go to Aoba Elementary School. I\'m in the second grade. My homeroom teacher is Mr. Sakai. Thank you.</p>', ja: '<h3>🎯 質問と答え / マイスピーチ</h3><p><span class="speaker">講師：</span>どこの小学校に通っていますか？</p><p><span class="speaker">りこ：</span>青葉小学校です。</p><p><span class="speaker">講師：</span>何年生ですか？</p><p><span class="speaker">りこ：</span>2年生です。</p><p><span class="speaker">講師：</span>あなたの担任の先生は誰ですか？</p><p><span class="speaker">りこ：</span>坂井先生です。</p><p><span class="speaker">講師：</span>今日は何曜日ですか？</p><p><span class="speaker">りこ：</span>水曜日です。</p><hr><p><span class="speaker">りこ：</span>こんにちは。わたしの名前はりこです。7歳です。青葉小学校に通っています。2年生です。わたしの担任の先生は、坂井先生です。ありがとうございました。</p>' },
21: { en: '<h3>💬 Hi, Henry! (10)</h3><p><span class="speaker">Henry:</span> Hi, Alan!</p><p><span class="speaker">Alan:</span> Hi, Henry.</p><p><span class="speaker">Henry:</span> How many gumballs do you have?</p><p><span class="speaker">Alan:</span> Ten. Do you want one?</p><p><span class="speaker">Henry:</span> Yes, I do!</p><p><span class="speaker">Alan:</span> Here you are.</p><p><span class="speaker">Henry:</span> Thank you!</p><p><span class="speaker">Mr. Brooks:</span> Hi, Henry and Alan!</p><p><span class="speaker">H&A:</span> Hi, Mr. Brooks!</p><p><span class="speaker">Mr. Brooks:</span> Alan, how many gumballs do you have?</p><p><span class="speaker">Alan:</span> Nine. Do you like gumballs?</p><p><span class="speaker">Mr. Brooks:</span> Yes, I do.</p><p><span class="speaker">Alan:</span> Here you are.</p><p><span class="speaker">Mr. Brooks:</span> Thank you.</p><p><span class="speaker">Alan:</span> Mr. Brooks, what are those?</p><p><span class="speaker">Mr. Brooks:</span> They\'re mushrooms.</p><p><span class="speaker">Henry:</span> How many mushrooms do you have, Mr. Brooks?</p><p><span class="speaker">Mr. Brooks:</span> Twenty.</p><p><span class="speaker">Alan:</span> Wow, they\'re beautiful.</p><p><span class="speaker">Mr. Brooks:</span> Do you want one?</p><p><span class="speaker">H&A:</span> Umm. No, I don\'t.</p><p><span class="speaker">Mr. Brooks:</span> Oh ...</p>', ja: '<h3>💬 やあ、ヘンリー！ (10)</h3><p><span class="speaker">ヘンリー：</span>やあ、アラン！</p><p><span class="speaker">アラン：</span>やあ、ヘンリー。</p><p><span class="speaker">ヘンリー：</span>チューインガムをいくつ持っているの？</p><p><span class="speaker">アラン：</span>10個。ひとつ欲しい？</p><p><span class="speaker">ヘンリー：</span>うん、欲しい！</p><p><span class="speaker">アラン：</span>はい、どうぞ。</p><p><span class="speaker">ヘンリー：</span>ありがとう！</p><p><span class="speaker">ブルックス先生：</span>やあ、ヘンリー、アラン！</p><p><span class="speaker">ヘ&ア：</span>こんにちは、ブルックス先生！</p><p><span class="speaker">ブルックス先生：</span>アラン、チューインガムをいくつ持っているんだい？</p><p><span class="speaker">アラン：</span>9個です。チューインガムは好きですか？</p><p><span class="speaker">ブルックス先生：</span>うん、好きだよ。</p><p><span class="speaker">アラン：</span>はい、どうぞ。</p><p><span class="speaker">ブルックス先生：</span>ありがとう。</p><p><span class="speaker">アラン：</span>ブルックス先生、それらは何ですか？</p><p><span class="speaker">ブルックス先生：</span>キノコだよ。</p><p><span class="speaker">ヘンリー：</span>キノコをいくつ持っているのですか、ブルックス先生？</p><p><span class="speaker">ブルックス先生：</span>20個だよ。</p><p><span class="speaker">アラン：</span>わあ、きれいですね。</p><p><span class="speaker">ブルックス先生：</span>ひとつ欲しいかい？</p><p><span class="speaker">ヘ&ア：</span>ええと。欲しくないです。</p><p><span class="speaker">ブルックス先生：</span>そうかい…。</p>' },
22: { en: '<h3>💬 Hi, Henry! (11)</h3><p><span class="speaker">Henry:</span> Hey, everyone! I can skip. Can you skip?</p><p><span class="speaker">A&N:</span> Yes, I can.</p><p><span class="speaker">Alan:</span> Can you skip and clap?</p><p><span class="speaker">Henry:</span> Yes, I can.</p><p><span class="speaker">Nina:</span> No, I can\'t. But can you sing?</p><p><span class="speaker">Alan:</span> Yes, I can. Can you sing and dance?</p><p><span class="speaker">Nina:</span> No, I can\'t.</p><p><span class="speaker">Henry:</span> That\'s amazing, Alan!</p><p><span class="speaker">Dragon Green:</span> Hi, everyone!</p><p><span class="speaker">H&A&N:</span> Hi, Dragon Green!</p><p><span class="speaker">Henry:</span> Can you dance?</p><p><span class="speaker">Dragon Green:</span> No, I can\'t. Can you fly?</p><p><span class="speaker">H&A&N:</span> No, I can\'t!</p>', ja: '<h3>💬 やあ、ヘンリー！ (11)</h3><p><span class="speaker">ヘンリー：</span>ねえ、みんな！ぼくはスキップができるんだ。スキップできる？</p><p><span class="speaker">ア&ニ：</span>うん、できるよ。</p><p><span class="speaker">アラン：</span>スキップしながら手をたたける？</p><p><span class="speaker">ヘンリー：</span>うん、できるよ。</p><p><span class="speaker">ニーナ：</span>わたしはできない。でも歌える？</p><p><span class="speaker">アラン：</span>うん、歌えるよ。歌いながら踊れるかい？</p><p><span class="speaker">ニーナ：</span>ううん、できないよ。</p><p><span class="speaker">ヘンリー：</span>すごい、アラン！</p><p><span class="speaker">ドラゴングリーン：</span>やあ、みんな！</p><p><span class="speaker">全員：</span>やあ、ドラゴングリーン！</p><p><span class="speaker">ヘンリー：</span>きみは踊れる？</p><p><span class="speaker">ドラゴングリーン：</span>ううん、踊れないよ。きみたちは飛べる？</p><p><span class="speaker">全員：</span>ううん、飛べなーい！</p>' },
23: { en: '<h3>🔤 Phonics: d, e, f</h3><p>dog - desk</p><p>egg - eggplant</p><p>fish - four</p>', ja: '<h3>🔤 フォニックス: d, e, f</h3><p>dog - イヌ / desk - 机</p><p>egg - タマゴ / eggplant - ナス</p><p>fish - 魚 / four - 4</p>' },
24: { en: '<h3>🌍 World Food</h3><p><span class="speaker">Ms. Wilson:</span> Looks delicious! This is ramen from Japan. What do people eat around the world? Let\'s go and see!</p><p><span class="speaker">Woman:</span> In Hungary, cabbage rolls are a popular dish.</p><p><span class="speaker">Woman:</span> In France, galette complète is a popular dish.</p><p><span class="speaker">Woman:</span> In Malaysia, Nasi Lemak is a popular dish.</p><p><span class="speaker">Woman:</span> In Sri Lanka, fish curry is a popular dish.</p><p><span class="speaker">Ms. Wilson:</span> Mmm. I want to try everything. Which country\'s food looks best to you?</p>', ja: '<h3>🌍 世界の食べ物</h3><p><span class="speaker">ウィルソン先生：</span>とてもおいしそうですね！これは日本のラーメンですね。世界中で、人々は何を食べているのでしょう？見に行きましょう！</p><p><span class="speaker">女性：</span>ハンガリーでは、ロールキャベツが人気の料理です。</p><p><span class="speaker">女性：</span>フランスでは、ガレットが人気の料理です。</p><p><span class="speaker">女性：</span>マレーシアでは、ナシレマが人気の料理です。</p><p><span class="speaker">女性：</span>スリランカでは、魚のカレーが人気の料理です。</p><p><span class="speaker">ウィルソン先生：</span>うーん。すべて食べてみたいですね。どこの国の料理が一番おいしそうに見えますか？</p>' },
25: { en: '<h3>🎵 The Calendar Song</h3>', ja: '<h3>🎵 カレンダーの歌</h3><p>※日本語訳省略</p>' },
26: { en: '<h3>🔤 Phonics: g, h, i, j</h3><p>goat - gumball</p><p>hat - happy</p><p>inchworm - in</p><p>jet - jump</p>', ja: '<h3>🔤 フォニックス: g, h, i, j</h3><p>goat - ヤギ / gumball - チューインガム</p><p>hat - 帽子 / happy - うれしい</p><p>inchworm - シャクトリムシ / in - 〜の中に</p><p>jet - ジェット機 / jump - とぶ</p>' },
,
27: { en: '<h3>U3-1 Hi, Henry! (12)</h3><p>Script available in class.</p>', ja: '<h3>U3-1 Hi, Henry! (12)</h3><p>スクリプトはクラスで確認できます。</p>' },
28: { en: '<h3>U3-2 Phonics k,l,m,n</h3><p>Script available in class.</p>', ja: '<h3>U3-2 Phonics k,l,m,n</h3><p>スクリプトはクラスで確認できます。</p>' },
29: { en: '<h3>U3-3 Hi, Henry! (13)</h3><p>Script available in class.</p>', ja: '<h3>U3-3 Hi, Henry! (13)</h3><p>スクリプトはクラスで確認できます。</p>' },
30: { en: '<h3>U3-4 Phonics o,p,q,r</h3><p>Script available in class.</p>', ja: '<h3>U3-4 Phonics o,p,q,r</h3><p>スクリプトはクラスで確認できます。</p>' },
31: { en: '<h3>U3-5 Hi, Henry! (14)</h3><p>Script available in class.</p>', ja: '<h3>U3-5 Hi, Henry! (14)</h3><p>スクリプトはクラスで確認できます。</p>' },
32: { en: '<h3>U3-6 Hi, Henry! (15)</h3><p>Script available in class.</p>', ja: '<h3>U3-6 Hi, Henry! (15)</h3><p>スクリプトはクラスで確認できます。</p>' },
33: { en: '<h3>U3-7 Phonics s,t,u,v</h3><p>Script available in class.</p>', ja: '<h3>U3-7 Phonics s,t,u,v</h3><p>スクリプトはクラスで確認できます。</p>' },
34: { en: '<h3>U3-8 Practice Q&A / Speech</h3><p>Script available in class.</p>', ja: '<h3>U3-8 Practice Q&A / Speech</h3><p>スクリプトはクラスで確認できます。</p>' },
35: { en: '<h3>U3-9 Phonics w,x,y,z</h3><p>Script available in class.</p>', ja: '<h3>U3-9 Phonics w,x,y,z</h3><p>スクリプトはクラスで確認できます。</p>' },
36: { en: '<h3>U3-10 Outdoor Activities</h3><p>Script available in class.</p>', ja: '<h3>U3-10 Outdoor Activities</h3><p>スクリプトはクラスで確認できます。</p>' },
37: { en: '<h3>U4-1 The Months of the Year</h3><p>Script available in class.</p>', ja: '<h3>U4-1 The Months of the Year</h3><p>スクリプトはクラスで確認できます。</p>' },
38: { en: '<h3>U4-2 At the Park</h3><p>Script available in class.</p>', ja: '<h3>U4-2 At the Park</h3><p>スクリプトはクラスで確認できます。</p>' },
39: { en: '<h3>U4-3 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U4-3 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
40: { en: '<h3>U4-4 The Rhyming Chant</h3><p>Script available in class.</p>', ja: '<h3>U4-4 The Rhyming Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
41: { en: '<h3>U4-5 Phonics -an,-en</h3><p>Script available in class.</p>', ja: '<h3>U4-5 Phonics -an,-en</h3><p>スクリプトはクラスで確認できます。</p>' },
42: { en: '<h3>U4-6 Wild Animals</h3><p>Script available in class.</p>', ja: '<h3>U4-6 Wild Animals</h3><p>スクリプトはクラスで確認できます。</p>' },
43: { en: '<h3>U4-7 The Pencil Case (2)</h3><p>Script available in class.</p>', ja: '<h3>U4-7 The Pencil Case (2)</h3><p>スクリプトはクラスで確認できます。</p>' },
44: { en: '<h3>U4-8 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U4-8 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
45: { en: '<h3>U4-9 Phonics -it,-ot</h3><p>Script available in class.</p>', ja: '<h3>U4-9 Phonics -it,-ot</h3><p>スクリプトはクラスで確認できます。</p>' },
46: { en: '<h3>U4-10 Where\'s the Key? (3)</h3><p>Script available in class.</p>', ja: '<h3>U4-10 Where\'s the Key? (3)</h3><p>スクリプトはクラスで確認できます。</p>' },
47: { en: '<h3>U4-11 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U4-11 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
48: { en: '<h3>U4-12 Phonics -ug,-ig</h3><p>Script available in class.</p>', ja: '<h3>U4-12 Phonics -ug,-ig</h3><p>スクリプトはクラスで確認できます。</p>' },
49: { en: '<h3>U4-13 Practice Q&A / Speech</h3><p>Script available in class.</p>', ja: '<h3>U4-13 Practice Q&A / Speech</h3><p>スクリプトはクラスで確認できます。</p>' },
50: { en: '<h3>U4-14 Rare Animals</h3><p>Script available in class.</p>', ja: '<h3>U4-14 Rare Animals</h3><p>スクリプトはクラスで確認できます。</p>' },
51: { en: '<h3>U5-1 Twinkle Twinkle</h3><p>Script available in class.</p>', ja: '<h3>U5-1 Twinkle Twinkle</h3><p>スクリプトはクラスで確認できます。</p>' },
52: { en: '<h3>U5-2 Grandma Likes Flowers (4)</h3><p>Script available in class.</p>', ja: '<h3>U5-2 Grandma Likes Flowers (4)</h3><p>スクリプトはクラスで確認できます。</p>' },
53: { en: '<h3>U5-3 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U5-3 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
54: { en: '<h3>U5-4 Phonics p,b</h3><p>Script available in class.</p>', ja: '<h3>U5-4 Phonics p,b</h3><p>スクリプトはクラスで確認できます。</p>' },
55: { en: '<h3>U5-5 Plants and Seeds</h3><p>Script available in class.</p>', ja: '<h3>U5-5 Plants and Seeds</h3><p>スクリプトはクラスで確認できます。</p>' },
56: { en: '<h3>U5-6 Mr. Hatrick (5)</h3><p>Script available in class.</p>', ja: '<h3>U5-6 Mr. Hatrick (5)</h3><p>スクリプトはクラスで確認できます。</p>' },
57: { en: '<h3>U5-7 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U5-7 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
58: { en: '<h3>U5-8 Phonics t,d</h3><p>Script available in class.</p>', ja: '<h3>U5-8 Phonics t,d</h3><p>スクリプトはクラスで確認できます。</p>' },
59: { en: '<h3>U5-9 Band-Aids and Erasers (6)</h3><p>Script available in class.</p>', ja: '<h3>U5-9 Band-Aids and Erasers (6)</h3><p>スクリプトはクラスで確認できます。</p>' },
60: { en: '<h3>U5-10 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U5-10 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
61: { en: '<h3>U5-11 Phonics c,g</h3><p>Script available in class.</p>', ja: '<h3>U5-11 Phonics c,g</h3><p>スクリプトはクラスで確認できます。</p>' },
62: { en: '<h3>U5-12 Practice Q&A / Speech</h3><p>Script available in class.</p>', ja: '<h3>U5-12 Practice Q&A / Speech</h3><p>スクリプトはクラスで確認できます。</p>' },
63: { en: '<h3>U5-13 Yummy Fruits</h3><p>Script available in class.</p>', ja: '<h3>U5-13 Yummy Fruits</h3><p>スクリプトはクラスで確認できます。</p>' },
64: { en: '<h3>U6-1 Bingo</h3><p>Script available in class.</p>', ja: '<h3>U6-1 Bingo</h3><p>スクリプトはクラスで確認できます。</p>' },
65: { en: '<h3>U6-2 Lunchtime with Grandma (7)</h3><p>Script available in class.</p>', ja: '<h3>U6-2 Lunchtime with Grandma (7)</h3><p>スクリプトはクラスで確認できます。</p>' },
66: { en: '<h3>U6-3 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U6-3 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
67: { en: '<h3>U6-4 Phonics m,n</h3><p>Script available in class.</p>', ja: '<h3>U6-4 Phonics m,n</h3><p>スクリプトはクラスで確認できます。</p>' },
68: { en: '<h3>U6-5 Work Vehicles</h3><p>Script available in class.</p>', ja: '<h3>U6-5 Work Vehicles</h3><p>スクリプトはクラスで確認できます。</p>' },
69: { en: '<h3>U6-6 The Cute Dress (8)</h3><p>Script available in class.</p>', ja: '<h3>U6-6 The Cute Dress (8)</h3><p>スクリプトはクラスで確認できます。</p>' },
70: { en: '<h3>U6-7 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U6-7 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
71: { en: '<h3>U6-8 Phonics f,v</h3><p>Script available in class.</p>', ja: '<h3>U6-8 Phonics f,v</h3><p>スクリプトはクラスで確認できます。</p>' },
72: { en: '<h3>U6-9 Whose Hat Is This? (9)</h3><p>Script available in class.</p>', ja: '<h3>U6-9 Whose Hat Is This? (9)</h3><p>スクリプトはクラスで確認できます。</p>' },
73: { en: '<h3>U6-10 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U6-10 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
74: { en: '<h3>U6-11 Phonics s,z</h3><p>Script available in class.</p>', ja: '<h3>U6-11 Phonics s,z</h3><p>スクリプトはクラスで確認できます。</p>' },
75: { en: '<h3>U6-12 Practice Q&A / Speech</h3><p>Script available in class.</p>', ja: '<h3>U6-12 Practice Q&A / Speech</h3><p>スクリプトはクラスで確認できます。</p>' },
76: { en: '<h3>U6-13 People and Work Vehicles</h3><p>Script available in class.</p>', ja: '<h3>U6-13 People and Work Vehicles</h3><p>スクリプトはクラスで確認できます。</p>' },
77: { en: '<h3>U7-1 The Birthday Poster (10)</h3><p>Script available in class.</p>', ja: '<h3>U7-1 The Birthday Poster (10)</h3><p>スクリプトはクラスで確認できます。</p>' },
78: { en: '<h3>U7-2 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U7-2 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
79: { en: '<h3>U7-3 Phonics l,r</h3><p>Script available in class.</p>', ja: '<h3>U7-3 Phonics l,r</h3><p>スクリプトはクラスで確認できます。</p>' },
80: { en: '<h3>U7-4 Marine Life</h3><p>Script available in class.</p>', ja: '<h3>U7-4 Marine Life</h3><p>スクリプトはクラスで確認できます。</p>' },
81: { en: '<h3>U7-5 Can You Do It? (11)</h3><p>Script available in class.</p>', ja: '<h3>U7-5 Can You Do It? (11)</h3><p>スクリプトはクラスで確認できます。</p>' },
82: { en: '<h3>U7-6 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U7-6 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
83: { en: '<h3>U7-7 Phonics w,y</h3><p>Script available in class.</p>', ja: '<h3>U7-7 Phonics w,y</h3><p>スクリプトはクラスで確認できます。</p>' },
84: { en: '<h3>U7-8 The Kazoo (12)</h3><p>Script available in class.</p>', ja: '<h3>U7-8 The Kazoo (12)</h3><p>スクリプトはクラスで確認できます。</p>' },
85: { en: '<h3>U7-9 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U7-9 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
86: { en: '<h3>U7-10 Phonics j,h</h3><p>Script available in class.</p>', ja: '<h3>U7-10 Phonics j,h</h3><p>スクリプトはクラスで確認できます。</p>' },
87: { en: '<h3>U7-11 Phonics k,x</h3><p>Script available in class.</p>', ja: '<h3>U7-11 Phonics k,x</h3><p>スクリプトはクラスで確認できます。</p>' },
88: { en: '<h3>U7-12 My Speech (1-16)</h3><p>Script available in class.</p>', ja: '<h3>U7-12 My Speech (1-16)</h3><p>スクリプトはクラスで確認できます。</p>' },
89: { en: '<h3>U7-13 Amazing Aquatic Life</h3><p>Script available in class.</p>', ja: '<h3>U7-13 Amazing Aquatic Life</h3><p>スクリプトはクラスで確認できます。</p>' },
90: { en: '<h3>U8-1 Let\'s Have Dinner (13)</h3><p>Script available in class.</p>', ja: '<h3>U8-1 Let\'s Have Dinner (13)</h3><p>スクリプトはクラスで確認できます。</p>' },
91: { en: '<h3>U8-2 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U8-2 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
92: { en: '<h3>U8-3 Art and Music</h3><p>Script available in class.</p>', ja: '<h3>U8-3 Art and Music</h3><p>スクリプトはクラスで確認できます。</p>' },
93: { en: '<h3>U8-4 Nice to Meet You (14)</h3><p>Script available in class.</p>', ja: '<h3>U8-4 Nice to Meet You (14)</h3><p>スクリプトはクラスで確認できます。</p>' },
94: { en: '<h3>U8-5 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U8-5 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
95: { en: '<h3>U8-6 My Speech (All)</h3><p>Script available in class.</p>', ja: '<h3>U8-6 My Speech (All)</h3><p>スクリプトはクラスで確認できます。</p>' },
96: { en: '<h3>U8-7 Mr. Hatrick\'s New Song (15)</h3><p>Script available in class.</p>', ja: '<h3>U8-7 Mr. Hatrick\'s New Song (15)</h3><p>スクリプトはクラスで確認できます。</p>' },
97: { en: '<h3>U8-8 Target Chant</h3><p>Script available in class.</p>', ja: '<h3>U8-8 Target Chant</h3><p>スクリプトはクラスで確認できます。</p>' },
98: { en: '<h3>U8-9 Native Art</h3><p>Script available in class.</p>', ja: '<h3>U8-9 Native Art</h3><p>スクリプトはクラスで確認できます。</p>' }
};
